#!/bin/bash

echo "npx personnalisé"

# Shift the first three arguments
shift
shift
shift

# Extract the first argument and quote it
first_arg="\"$1\""

# Shift the first argument
shift

echo ">>> $first_arg $@"
# Pass the first argument (quoted) along with the rest to npx
/usr/bin/npx playwright test "$first_arg" "$@"
