#!/bin/bash

echo "npx personnalisé"

# Shift the first three arguments
shift
shift
shift

# Print the remaining arguments
echo "$@"

# Call the npx command with the remaining arguments
/usr/bin/npx playwright test "$@" -c bdd_playwright/playwright.conf.js
